### ISSUE TITLE
کار نکردن برنامه

### ISSUE THREAD

**Issue by ShahramNo** [RezaParsian/Divar#1]
سلام . برنامه  ربات دیوار من نتونستم اجرا کنم. فایلهاش ناقص هست. و حتی با ساختن فایلها باز هم برنامه ارور دارد. لطفا راهنمایی کنید. ممنون

**Comment by RezaParsian** [comment]
> سلام . برنامه ربات دیوار من نتونستم اجرا کنم. فایلهاش ناقص هست. و حتی با ساختن فایلها باز هم برنامه ارور دارد. لطفا راهنمایی کنید. ممنون

سلام وقتتون بخیر!
متاسفانه دسترسی به سیستم ویندوز و سی‌شارپ ندارم
ولی میتونم براتون api رو که داخل [سایتم](https://rp76.ir/blog/post/%D8%B1%D8%A7%D8%A8%D8%B7-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87%E2%80%8C%D9%86%D9%88%DB%8C%D8%B3%DB%8C-%D8%AF%DB%8C%D9%88%D8%A7%D8%B1-Api-%D8%AF%DB%8C%D9%88%D8%A7%D8%B1) انتشار دادم رو قرار بدم!

**Comment by ShahramNo** [comment]
خیلی ممنونم ازتون . اره اگر ممکنه ‌‌ خیلی ممنونم

**Comment by RezaParsian** [comment]
> خیلی ممنونم ازتون . اره اگر ممکنه ‌‌ خیلی ممنونم

https://rp76.ir/blog/post/%D8%B1%D8%A7%D8%A8%D8%B7-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87%E2%80%8C%D9%86%D9%88%DB%8C%D8%B3%DB%8C-%D8%AF%DB%8C%D9%88%D8%A7%D8%B1-Api-%D8%AF%DB%8C%D9%88%D8%A7%D8%B1

**Comment by ShahramNo** [comment]
> > خیلی ممنونم ازتون . اره اگر ممکنه ‌‌ خیلی ممنونم
> 
> https://rp76.ir/blog/post/%D8%B1%D8%A7%D8%A8%D8%B7-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87%E2%80%8C%D9%86%D9%88%DB%8C%D8%B3%DB%8C-%D8%AF%DB%8C%D9%88%D8%A7%D8%B1-Api-%D8%AF%DB%8C%D9%88%D8%A7%D8%B1

من باز کردم. کد ها کار نمیکنن. متاسفانه چون ظاهرا تغیراتی توی ایدوار انفاق افتاده. مثلا شهرهارو نمیتونه دریافت کنه. و خطا داره
InnerException={"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:8118..."}
این هم متن خطا توی خط 
   result = wb.DownloadString(url);
چون مقدار  
result 
نال هست

**Comment by RezaParsian** [comment]
> > > خیلی ممنونم ازتون . اره اگر ممکنه ‌‌ خیلی ممنونم
> > 
> > 
> > https://rp76.ir/blog/post/%D8%B1%D8%A7%D8%A8%D8%B7-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87%E2%80%8C%D9%86%D9%88%DB%8C%D8%B3%DB%8C-%D8%AF%DB%8C%D9%88%D8%A7%D8%B1-Api-%D8%AF%DB%8C%D9%88%D8%A7%D8%B1
> 
> من باز کردم. کد ها کار نمیکنن. متاسفانه چون ظاهرا تغیراتی توی ایدوار انفاق افتاده. مثلا شهرهارو نمیتونه دریافت کنه. و خطا داره InnerException={"No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:8118..."} این هم متن خطا توی خط result = wb.DownloadString(url); چون مقدار result نال هست

شما توی واتساپ با من تماس بگیرید
سعی میکنم کمکتون کنم!
09174811484
